
ALTER TABLE containers
MODIFY client_code VARCHAR(50) NOT NULL,
MODIFY client_name VARCHAR(255) NOT NULL,
MODIFY loading_number VARCHAR(50) NOT NULL UNIQUE,
MODIFY carton_count INT NOT NULL,
MODIFY container_number VARCHAR(100) NOT NULL UNIQUE,
MODIFY bill_number VARCHAR(100) NOT NULL,
MODIFY category VARCHAR(100) NOT NULL,
MODIFY carrier VARCHAR(100) NOT NULL,
MODIFY registry VARCHAR(100) NOT NULL,
MODIFY weight VARCHAR(50) NULL,
MODIFY expected_arrival DATE NOT NULL,
MODIFY ship_name VARCHAR(100) NOT NULL,
MODIFY custom_station VARCHAR(100) NOT NULL,
MODIFY notes TEXT NULL,
MODIFY release_status ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
MODIFY company_release ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
MODIFY office VARCHAR(50) NOT NULL;
