name: nokta_pos_monorepo
description: "نظام نوكتا لنقاط البيع - Multi-App Flutter Monorepo"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod: ^2.4.9
  provider: ^6.1.1
  
  # HTTP & API
  dio: ^5.4.0
  http: ^1.1.0
  retrofit: ^4.1.0
  
  # Local Storage & Database
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.0+2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Security & Authentication
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1
  crypto: ^3.0.3
  
  # Navigation & Routing
  go_router: ^12.1.3
  auto_route: ^7.9.2
  
  # Payment Integration
  stripe_sdk: 5.0.0
  
  # Utilities
  path: ^1.9.0
  uuid: ^4.2.1
  equatable: ^2.0.5
  
  # Code Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
  # UI & Design
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Pagination & Lists
  infinite_scroll_pagination: ^4.0.0
  
  # Firebase (Optional)
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9

dependency_overrides:
  # Override for compatibility
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  
  # Code Analysis
  very_good_analysis: ^5.1.0
  
  # Testing
  mocktail: ^1.0.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
