name: pos_app
description: "نقطة - نظام نقاط البيع المتقدم"
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Core dependencies
  core:
    path: ../../packages/core
  
  # State management
  flutter_riverpod: ^2.4.9
  riverpod: ^2.4.9
  
  # UI dependencies
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  # Routing
  go_router: ^12.1.3
  
  # Local storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Network
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  connectivity_plus: ^5.0.2
  
  # Device features
  permission_handler: ^11.1.0
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  
  # Printing
  esc_pos_printer: ^4.1.0
  esc_pos_utils: ^1.1.0
  blue_thermal_printer: ^1.2.4
  
  # Barcode scanning
  qr_code_scanner: ^1.0.1
  
  # Utils
  intl: ^0.19.0
  logger: ^2.0.2+1
  uuid: ^4.2.1
  
  # Image handling
  image_picker: ^1.0.4
  
  # Animations
  lottie: ^2.7.0
  
  # Date and time
  jiffy: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - lib/assets/images/
    - lib/assets/icons/
    - lib/assets/lottie/
    
  fonts:
    - family: Cairo
      fonts:
        - asset: lib/assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Cairo-ExtraBold.ttf
          weight: 800
          
    - family: Roboto
      fonts:
        - asset: lib/assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Roboto-Bold.ttf
          weight: 700
          
    - family: NoktatIcons
      fonts:
        - asset: lib/assets/fonts/NoktatIcons.ttf

flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/generated
  
dependency_overrides:
  intl: ^0.19.0